///////////////////////////////////////////////////////////
//  Customer.cs
//  Implementation of the Class Customer
//  Generated by Enterprise Architect
//  Created on:      18-jun-2015 16:48:05
//  Original author: Geert Van Laethem
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Eas.Tests {
	public class Customer {

		public Customer(){

		}

		~Customer(){

		}

		/// 
		/// <param name="id"></param>
		public int GetCustomer(int id){

			return 0;
		}

		public int GetCustomers(){

			return 0;
		}

	}//end Customer

}//end namespace Tests