///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      18-jun-2015 16:48:05
//  Original author: Geert Van Laethem
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Eas.Tests {
	public class Person {

		public Person(){

		}

		~Person(){

		}

		/// 
		/// <param name="id"></param>
		public int GetPerson(int id){

			return 0;
		}

		public int GetPersons(){

			return 0;
		}

	}//end Person

}//end namespace Tests