///////////////////////////////////////////////////////////
//  TurnOnLight.cs
//  Implementation of the Class TurnOnLight
//  Generated by Enterprise Architect
//  Created on:      18-jun-2015 16:48:05
//  Original author: Geert Van Laethem
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Eas.Tests {
	public class TurnOnLight {

		public TurnOnLight(){

		}

		~TurnOnLight(){

		}

		[Fact(DisplayName = "Light cannot be recovered from the system writes entry in log")]
		public void LightNotAvailableAddLogEntry(){

		}

		[Fact(DisplayName = "Light cannot be recovered from the system ignites alarm")]
		public void LightNotAvailableAlarm(){

		}

		[Fact(DisplayName = "Light cannot be recovered from the system throws exception")]
		public void LightNotAvailableThrowException(){

		}

		[Fact(DisplayName = "System asks LightModule for specific light")]
		public void SystemAsksSpecificLight(){

		}

		[Fact(DisplayName = "TurnOffLight")]
		public void TurnOff(){

		}

		[Fact(DisplayName = "TurnOnLight")]
		public void TurnOn(){

		}

		[Fact(DisplayName = "System asks Light Module for specific light and not found adds log entry")]
		public void WhenLightNotFoundAddLogEntry(){

		}

		[Fact(DisplayName = "System asks Light Module for specific light and not found throws exception")]
		public void WhenLightNotFoundThrowException(){

		}

	}//end TurnOnLight

}//end namespace Tests